### ISSUE TITLE
Proper win/lose events

### ISSUE THREAD

**Issue by ryondinkus** [Jjman739/InsiderPerspective#12]
Also needed for the playtest. Touching the tile should show a proper game over screen, and we should have a basic relic that can be grabbed to show a winscreen.

Also maybe consider putting in a game over screen if the player is seen on the unfrozen camera? Might not be necessary for playtest.

**Comment by lawrencemsteven** [comment]
For now we might want to consider just having a point system and a time limit. So the players have X amount of time and every item they grab and loot they get money for.

**Comment by lawrencemsteven** [comment]
Blocked by #28
