### ISSUE TITLE
Laser surprise trap

### ISSUE THREAD

**Issue by ryondinkus** [Jjman739/InsiderPerspective#13]
The cool surprise trap from the LARP the other day.

The laser will activate when the camera is frozen, and periodically fire at the player. The laser has a code on it that only the thief can see. The thief can read that code to the security guard, who can deactivate it on their end.

Should the camera unfreeze, the laser will stop.

We can try to shoot for the playtest with this one but it might be too much.

![image](https://github.com/Jjman739/InsiderPerspective/assets/60999059/6e3d97b9-62cb-4245-a60c-903bcdc0429c)

**Comment by lawrencemsteven** [comment]
We might want to work on this after the pre-alpha, at the very least I think that it should be low priority over the other things especially since this will probably take quite a bit of work.
